---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install some packages
    yum:
      name:
        - java-1.8.0-openjdk-devel.x86_64
        - git
        - docker
        - curl
        - wget
      state: present

  - name: start docker service
    service: name=docker state=started
